name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          cache: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.2
          args: ./...
        env:
          CGO_ENABLED: "0"
          GOLANGCI_LINT_CACHE: ${{ github.workspace }}/.cache/golangci

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          cache: true
      - name: Run tests
        env:
          CGO_ENABLED: "0"
          GOCACHE: ${{ github.workspace }}/.cache/go-build
        run: go test ./...
